name: Docker Image CI

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*.*'

env:
  IMAGE_NAME: ghcr.io/${{ github.repository }}

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Set env
        run: echo "IMAGE_VERSION=${GITHUB_REF/refs\/tags\/v/}" >> ${GITHUB_ENV}

      - uses: actions/checkout@v2

      - name: Build the Docker image
        run: |
          docker build . --file Dockerfile --tag "${IMAGE_NAME}:${IMAGE_VERSION}"
          docker tag "${IMAGE_NAME}:${IMAGE_VERSION}" "${IMAGE_NAME}:latest"

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push to GitHub Container Registry
        run: |
          docker push "${IMAGE_NAME}:${IMAGE_VERSION}"
          docker push "${IMAGE_NAME}:latest"
