name: Pull Docker image from ghcr.io

on:
  workflow_dispatch:
  push:
    tags:
      - 'pull-test*'

jobs:
  pull_image:
    runs-on: ubuntu-latest

    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pull from GitHub Container Registry
        run: |
          docker pull ghcr.io/nor3blk/ccs-cc26xx-docker/ccs-cc26xx-docker:latest
